[info]
relay_url = "wss://relay.nateeatschicken.xyz/"
name = "NateEatsChicken Relay"
description = "Friendly relay for NateEatsChicken + power users. Light anti-spam, paid handles, and relay access."
pubkey = "b12b6d90b7ba7b6d4432b272b10a4983d22ebdae5defd9aacfe54d158a0fdd0d"
contact = "npub1ky4kmy9hhfak63pjkfetzzjfs0fza0dwthhan2k0u4x3tzs0m5xsh9mgd2"
software = "nostr-rs-relay"
supported_nips = [1, 2, 9, 11, 15, 16, 20, 33, 40]

[network]
address = "0.0.0.0"
port = 8080

[options]
reject_future_seconds = 1800

[limits]
messages_per_sec = 10
subscriptions_per_min = 60
max_event_bytes = 65536

[verified_users]
mode = "passive"
domain_whitelist = ["relay.nateeatschicken.xyz"]

[authorization]
pubkey_whitelist = []
