[info]
relay_url  = "wss://relay.nateeatschicken.xyz/"
name       = "NateeatsChicken Relay"
description= "Read: open. Write: members only to keep spam out."

[network]
address = "0.0.0.0"
port    = 8080

[options]
reject_future_seconds = 1800

[limits]
# Keep defaults for now

[authorization]
pubkey_whitelist = [
  "b12b6d90b7ba7b6d4432b272b10a4983d22ebdae5defd9aacfe54d158a0fdd0d"
]
